### ISSUE TITLE
ignores https in mixed sites

### ISSUE THREAD

**Issue by pumpi** [lgraubner/sitemap-generator-cli#3] opened 2016-03-30 13:56 UTC
when i make an sitemap for my page https://www.parkhotel-burgmuehle.de he ignores a lot of URLs but the robots.txt says allowed an i dont know why

as exampel this urls are ignored:
https://www.parkhotel-burgmuehle.de/blog/holiday-check-award-2016/
https://www.parkhotel-burgmuehle.de/blog/die-weihnachtsmaerkte-im-oberallgaeu/
https://www.parkhotel-burgmuehle.de/blog/w-lan-der-burgmuehle/
https://www.parkhotel-burgmuehle.de/impressum

and in the robtots.txt only this lines
User-agent: *
Disallow: */feed/
Disallow: */page/*

**Comment by lgraubner** [comment] 2016-03-30 14:22
It works for me:

![screenshot 2016-03-30 16 21 01](https://cloud.githubusercontent.com/assets/2519959/14145243/73134a9a-f693-11e5-9972-ba6b2bc2860a.png)

Although I noticed another entry with `/feed/` attached. This is ignored as expected.

**Comment by pumpi** [comment] 2016-03-31 08:49
Ok i test again and now i can give you mor informations.

if i start the generator with the https all is fine if i start with http he ignore all https links

**Comment by lgraubner** [comment] 2016-03-31 08:54
You are not redirecting from http to https. The generator crawls your site and follows all links. This is a problem on your end and not within the generator, so I'm closing this issue.

**Comment by pumpi** [comment] 2016-03-31 09:21
Sorry but i cannot accept your Answer. When i have an mixed Side with https and http then the generator ignores one of theme this is not right

**Comment by lgraubner** [comment] 2016-03-31 09:58
I made more checks and can confirm your problem, you are right. ;) Although I'm not sure whats the problem. Will have to investigate this further.

**Comment by DennisBecker** [comment] 2016-04-05 07:53
I found a problem on my side: there is no robots.txt on HTTPS - and also it redirects from /robots.txt to http://example.com which leads to a HTTP response code 200

I'll fix this and provide a proper robots.txt for HTTPS

**Comment by lgraubner** [comment] 2016-05-20 09:25
Fixed with v4.0.0

**Closed by lgraubner** 2016-05-20 09:25 UTC
Labels: bug

**Comment by pumpi** [comment] 2016-05-20 11:58
im no have the problem that my side not crawl the blog (this is the https part of the side) and when in put in the direkt adress as https he says he cannot find. If i get the url without http he jumps down to the root and never go back in the blog but there are a lot of other links in the blog

`sitemap-generator -d https://parkhotel-burgmuehle.de/blog/`

**Comment by lgraubner** [comment] 2016-05-20 12:26
First of all I can see that all of your pages are available with and without https. You should redirect all requests to https or you get duplicate content. Just a general advice.
I can confirm that there is a problem directly getting `https://parkhotel-burgmuehle.de/blog/`. Will have to look at it later in detail.
Another thing: If you want to crawl only pages beneath the initial url you have to set `--baseurl`.
